### ISSUE TITLE
Ctrl+enter doesn't work when editing existing messages

### ISSUE THREAD

**Issue by FarisHijazi** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#17]
hello and thank you for this extension.

It doesn't work when I go back to edit my existing message and then click Ctrl+Enter in OpenAI

**Comment by masachika-kamada** [comment]
@FarisHijazi 

Thank you for bringing this to our attention.

You are correct that the current version of the "ChatGPT Ctrl+Enter Sender" extension supports Ctrl+Enter for message sending, but not for editing already sent messages.

Given your valuable suggestion, we are considering adding support for Ctrl+Enter when editing sent messages in our next version update. We kindly ask for your patience as we work on this enhancement.

Thank you for using the "ChatGPT Ctrl+Enter Sender" extension, and we appreciate your continued support.

**Comment by masachika-kamada** [comment]
@FarisHijazi

I'm pleased to inform you that the latest version of the "ChatGPT Ctrl+Enter Sender" extension (v1.2.0) now supports using Ctrl+Enter for editing already sent messages.

We appreciate your valuable suggestion that led to this enhancement. We hope you find this new feature useful.

Thank you for your continued support of the "ChatGPT Ctrl+Enter Sender" extension.

Best regards
