### ISSUE TITLE
Firefox版の拡張機能の作成予定について

### ISSUE THREAD

**Issue by Aniny21** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#20]
こんにちは、素晴らしい拡張機能を開発してくださりありがとうございます。

私はFirefoxを主要ブラウザとして使用しているため、この拡張機能のFirefox版があれば非常にありがたいのですが、Firefox版の開発の予定はありますか？

**Comment by masachika-kamada** [comment]
@Aniny21 
ご興味持っていただきありがとうございます。
Firefox でのリリースの予定はありませんでしたが、こちらで検討してみます。
リリースする際にはまたご連絡いたします。
引き続きよろしくお願いいたします。

**Comment by Aniny21** [comment]
迅速なご返信ありがとうございます。

この拡張機能のFirefox版が楽しみで待ちきれなかったため、個人的にテストしてみましたところ、FirefoxのManifest V3対応状況が悪いためV2に落とす必要がありましたが、いくつかのAPIを変更し似たような動作を再現することができました。

差し出がましいとは存じますが、もし詳しい情報が必要でしたらお知らせください。

拡張機能の発展と多くのユーザーへの提供を心から応援しております。

**Comment by masachika-kamada** [comment]
@Aniny21 
Firefox 対応に向けた情報のご提供、誠にありがとうございます。

https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/tree/firefox-dev
こちらのブランチを Firefox 向けの拡張機能開発ブランチとして公開いたしました。
私自身、Firefox の拡張機能を作成したことがなく、Firefox への対応のためのコード修正に時間を要してしまうため、大変恐縮ですがこのブランチに向けて Pull Request を出していただけますと幸いです。

私も @Aniny21 様と同じく多くのユーザーへの利便性の向上が最重要だと考えておりますので、@Aniny21 様ご自身で ChatGPT Ctrl+Enter Sender を Firefox 対応させたものを公開していただいても構いません。

貴重なご意見いただきありがとうございます。

**Comment by masachika-kamada** [comment]
@Aniny21 
Pull Request 誠にありがとうございます。マージいたしました。
私も `data` が未定義になることに関して Firefox では `chrome` ではなく `browser` に置き換える必要があるとの記載を見つけたため、私も検証を進めてみます。
引き続きよろしくお願いいたします。

**Comment by Aniny21** [comment]
マージありがとうございます。
`chrome`と`browser`についてはcallbackかPromiseかなど細かい挙動の違いがあるようなので、storage系の処理はかなり書き換える必要があるかもしれません。
引き続き検証させていただきます。

**Comment by Aniny21** [comment]
いくつかの変更を加え、とりあえずFirefox版でChrome版と同じ動作を再現することができました。
Pull Requestのご確認をよろしくお願いいたします。

**Comment by masachika-kamada** [comment]
コード修正ありがとうございます。
Firefox にて Chrome と同じ動作を確認できたためマージいたしました。
動作に関して問題ないと考えられるためリリース作業を進めたいと思いますがいかがでしょうか。
また、README にコントリビュータとしてアカウント名を掲載してもよろしいでしょうか。

**Comment by Aniny21** [comment]
ご連絡いただき、ありがとうございます。
リリース作業の進行について、問題ございません。何か私にお手伝いできることがございましたら、ご遠慮なくお申し付けください。

また、README に私のアカウント名をコントリビュータとして記載していただくことを提案していただき、大変光栄に思います。是非ともお願い申し上げます。

引き続きよろしくお願いいたします。

**Comment by masachika-kamada** [comment]
リリースの申請が完了いたしました。
審査が完了すると以下のページからダウンロードできるようになるとのことでした。
https://addons.mozilla.org/ja/firefox/addon/chatgpt-ctrl-enter-sender/
お力添えいただき誠にありがとうございました。
![image](https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/assets/63488322/169f87fd-a58f-4aa0-a2ac-0f91ac2c64e7)

**Comment by Aniny21** [comment]
リリースの申請が完了されたとのこと、ご報告いただきありがとうございます。
審査が通り、アドオンが使えるようになるのを心待ちにしております。
