### ISSUE TITLE
[Feature Request] Add support for Bing Chat

### ISSUE THREAD

**Issue by aiirobyte** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#29]
**Is your feature request related to a problem? Please describe**.  
A clear and concise description of what the problem is Bing Chat only using `Shift+Enter` to start a new line, other modifier with `Enter` is just sending, this is annoying especially when switching between different products.

**Describe the solution you'd like**.    
Only Using `Ctrl+Enter` to send, others just to start a new line.

**Describe alternatives you've considered**.   
Have considered to let user customize the send key?

Appreciate for your great work, thanks!

**Comment by masachika-kamada** [comment]
@aiirobyte 

Thank you for your suggestion to enhance our extension by expanding the customizability of the send key for Bing Chat. It's a valuable idea and I'm grateful for your contribution. I will definitely consider this for inclusion in our next update.

We highly value user suggestions and aim to continually improve our extension based on such feedback.
