### ISSUE TITLE
Feature Request: ADD plugin/option: Enter send message (not opens file upload)

### ISSUE THREAD

**Issue by allanlaal** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#35]
**Is your feature request related to a problem? Please describe**.  

ChatGPT has this bug, where starting from the 2nd message every time you hit Enter (before installing this extension), it would open the file upload dialog - sometimes it sends and opens the dialog at the same time

**Comment by masachika-kamada** [comment]
Thank you for the feature request. To help us understand and address the issue more effectively, could you provide more details? Specifically:

- The exact steps you take on the ChatGPT site when the issue occurs. Just a brief description of what leads to the problem would be very helpful.
- A screenshot or short video of the issue, if possible.

This information will greatly assist us in reproducing and fixing the issue. Thank you for your help!

**Comment by masachika-kamada** [comment]
Thank you for the feature request. As we haven't received any updates, we will be closing this issue for now. Feel free to reopen or create a new issue with more details if needed.

**Comment by allanlaal** [comment]
I want Enter to send the message, not Ctrl+Enter
