### ISSUE TITLE
Claudeでうまく動作していないように見えます

### ISSUE THREAD

**Issue by kenzo-tanaka** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#41]
> Please provide us with the following information:
> ---------------------------------------------------------------

まず、素晴らしい拡張機能の提供ありがとうございます！

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Claudeでこちらの拡張機能が正常に動作していないように見えるため報告いたします。
（有料課金の状態）

### Steps to reproduce
1. [ストア](https://chromewebstore.google.com/detail/chatgpt-ctrl+enter-sender/gbncgdhklmnckojlibfhdadpfbcdbnch?hl=ja)からインストール
2. ポップアップをクリックすると下記キャプチャのような表示になる。また、Enterキーのみで送信が実行される。
  ![スクリーンショット 2024-03-31 14 40 35のコピー](https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/assets/33926355/3e69d9e0-87a3-4110-8dc9-49c5d73ae01f)
3. チャット詳細画面でもポップアップは下記キャプチャの表示で、Enterキーのみで送信が実行される。
  ![スクリーンショット 2024-03-31 14 41 51のコピー](https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/assets/33926355/08897af4-d458-49bb-ba4b-dffbbeb2e019)  

**Expected behavior** [What you expected to happen.]

* ポップアップをクリックした際は、ChatGPTアクセス時と同じく下記の様な表示になるのが正しい挙動でしょうか。
  ![スクリーンショット 2024-03-31 14 44 05](https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/assets/33926355/f2bb9875-ba7b-4106-b8f8-9da39a654e78) 
* ClaudeでもEnterキーによる送信は制御されている状態。

**Actual behavior** [What actually happened.]

上述の通り。

**Screenshots**         

### Additional context
Ex. Ex. Your environment (OS and browser, and their versions)

* Google Chrome バージョン: 123.0.6312.59（Official Build） （arm64）
* macOS Sonoma バージョン14.4.1

**Comment by kenzo-tanaka** [comment]
related: #38 #39

**Comment by kenzo-tanaka** [comment]
もしかして上記アップデートはストア上には反映されていないのでしょうか？？

**Comment by masachika-kamada** [comment]
@kenzo-tanaka 
ありがとうございます。
現在、Chromeウェブストアにてアップデート申請手続き中のためClaudeとCopilotへの対応が遅れております。
もうしばらくお待ちいただけますと幸いです。

**Comment by kenzo-tanaka** [comment]
失礼しました🙇‍ 待っております！

**Comment by kenzo-tanaka** [comment]
こちらはcloseしておきます。
