### ISSUE TITLE
Perplexity AIのトップページでCtrl+Enter送信すると、同内容のスレッドが2つ作成される

### ISSUE THREAD

**Issue by istallia** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#43]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### 説明
- Perplexity AIのトップページにてCtrl+Enterで質問文を送信すると、同じ質問文のスレッドが2つ作成されてしまいます。
- 「New Thread (Ctrl+I)」で表示されるモーダルウィンドウでは、この問題は発生しません。
- また、送信ボタンをマウスクリックすることで送信する方式でも、問題は発生しません。

### 再現手順
1. [Perplexity AIのトップページ](https://perplexity.ai)にアクセスする。
2. テキストエリアに質問文を入力し、Ctrl+Enter操作で送信する。
    - このとき、Proツールの有効/無効状態は関係ない。
3. 表示されかけた検索結果が消え、最初から再生成される挙動を確認する。
4. [ライブラリ](https://www.perplexity.ai/library)にて、同じ質問文のスレッドが2つ存在することを確認する。

### 推測される原因
試しに`event.target.dispatchEvent(new KeyboardEvent("keydown", ...))`をコメントアウトしたところ、症状は再現しなくなりました。
このことから、おそらく通常のkeydownイベントとスクリプトで用意したkeydownイベントの2つがほぼ同時に発火していることに起因していると思われます。

### 補足
OS: Windows 10 Home
Browser: Google Chrome 123.0.6312.124 (Official Build)
なお、WebChatGPTとTalkBerryは使用していません。また、広告ブロッカーは無効化しています。

**Comment by masachika-kamada** [comment]
@istallia 
ご指摘いただきありがとうございます！
修正いたしますので反映まで少々お待ちください。
