### ISSUE TITLE
Firefox - Claude not included in permissions list of websites

### ISSUE THREAD

**Issue by probablytukars** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#49]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

I am moving from chromium-based to firefox (again) due to several issues I have had with chromium-based browsers. The chromium extension includes claude.ai (one of my favourite ai websites) however on firefox does not include claude :(. I am hoping it is a really simple fix since it already exists on chromium (I think there are some other websites missing from the list too).

It just means that the ctrl+enter sending isn't working for claude on firefox due to it missing from the permissions list I think. I would really appreciate an update soon, thank you :).

### Steps to reproduce
1. Go to https://claude.ai/chats
2. type and press enter. it sends on enter

**Expected behavior** [What you expected to happen.]
it doesn't send on enter

**Actual behavior** [What actually happened.]
it sends on enter

**Screenshots**         

### Additional context
Ex. Ex. Your environment (OS and browser, and their versions)
Firefox, Windows

**Comment by masachika-kamada** [comment]
@probablytukars Thank you for bringing this to our attention.

We currently don't have immediate plans to update the Firefox version of the extension, so it might take some time before any updates are made. We apologize for the inconvenience. For the best experience, we recommend using the Chromium-based browser where this feature is available.

Thank you for your understanding and patience.
