### ISSUE TITLE
ChatGPT Changed URL TO https://chatgpt.com/

### ISSUE THREAD

**Issue by bozliu** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#56]
Please update URLs on Firefox addson

**Comment by vordan** [comment]
> Please update URLs on Firefox addson

Not just on Firefox, but on Chrome/Chromium based browsers

**Comment by manota** [comment]
I read the comments on google addon page, I think already addon on google chrome is fixed.
But, Firefox is not now.
Please fix it as soon as possible.

**Comment by manota** [comment]
@masachika-kamada 
Do you have the plan to fix this addon of Firefox?
If so, please tell me when you will finish fixing it.

**Comment by masachika-kamada** [comment]
@manota 
I have just submitted the update to the store. Please wait for it to be reflected.
