### ISSUE TITLE
Does not work when used with the extension "chatgptの音声コントロール"

### ISSUE THREAD

**Issue by monkey999por** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#57]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
If you install this extension and the ["chatgpt voice control"](https://voicewave.xyz/ja/) extension at the same time, 
the process of pressing the send button of this extension "chatgpt voice control" will crash and not work.

### Steps to reproduce
1. Install this extention.
2. Install extention ["chatgpt voice control"](https://voicewave.xyz/ja/) extension
3. Open Chatgpt and input something, say "enter"

**Expected behavior** [What you expected to happen.]
the both of extentions are working fine.

**Actual behavior** [What actually happened.]
If I install just one of them, it works fine

**Screenshots**         

### Additional context
```
OS: Windows 11
Chrome:  128.0.6613.138（Official Build） （64 bit）
```

**Comment by masachika-kamada** [comment]
@monkey999por 
Chrome extensions are individually developed by different developers, and due to dependencies and other factors, they may not function properly. If unintended behavior occurs, please disable one of the extensions to resolve the issue. We apologize for any inconvenience and appreciate your understanding.
