### ISSUE TITLE
ChatGPT Ctrl+Enter Sender Extension Not Working in Firefox

### ISSUE THREAD

**Issue by DryTrolox** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#58]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
If the input form is empty, the addon works.
However, if any value is entered, the addon doesn't function.
Pressing Enter will send the message.

### Steps to reproduce
1.Access the ChatGPT website.
2.In the input form, type any message.
3.Press the Enter key.
4.The message will be sent.

**Expected behavior** [What you expected to happen.]
When pressing the Enter key, it should create a new line, and pressing Ctrl+Enter should send the message.

**Actual behavior** [What actually happened.]
Pressing the Enter key sends the message, and the Extension  does not work.

**Screenshots**         
none

### Additional context
OS :Microsoft Windows 11 Pro
OS Ver:10.0.22631 N/A Build 22631
Browser:Firefox 130.0dd-on does not work.

**Comment by pmopmo** [comment]
I have the same issue on FF 130.0.1, Windows 10 Enterprise v 19045.4780

**Comment by ash0923** [comment]
I also faced the same issue. I think it's probably something that stopped working with the latest update.

**Comment by sahksas** [comment]
I made the fixes in the following PR:
- https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/pull/59

**Comment by ash0923** [comment]
Extension is invalid

Reading manifest: Error processing background: Value must either: contain the required "page" property, contain the required "scripts" property, or not contain an unexpected "type" property
まだありません。

**Comment by DryTrolox** [comment]
I might be doing something wrong, but I am also getting the above error.

**Comment by sahksas** [comment]
@ash0923 @DryTrolox 
フィードバックありがとうございます！

コメント頂いている事象は、 https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/pull/59 のコードで発生していることでしょうか？
よろしければ事象が再現する手順をご教授いただけると幸いです。

また、修正後の結果に関する報告はPR側のコメントにいただけると幸いです。

---

thx for your feedback!

Is the issue you're commenting on occurring in the code from https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/pull/59 ? If possible, I would appreciate it if you could provide the steps to reproduce the issue.

Also, it would be helpful if you could report the results after the fix in the comments on the PR.

**Comment by sahksas** [comment]
> [!tip]
> `main`ブランチで拡張機能を読み込んだところ、報告頂いているスクリーンショットと同じ表示を再現しました。
>PRの内容をお試し頂く場合は、`sahksas:1.5.2-to-firefox`ブランチを使用してください。
> 
> ---
> 
> When I loaded the extension on the `main` branch, I was able to reproduce the same display as shown in the screenshot provided.
> If you would like to try the contents of the https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/pull/59 , please use the `sahksas:1.5.2-to-firefox` branch.

![image](https://github.com/user-attachments/assets/7748d8e1-c9ed-4f00-91fa-52460fb10e4a)

**Comment by sahksas** [comment]
@DryTrolox 
PRが作成されているだけで不具合の解消はされていませんので、Reopenお願いします。

---

The issue has not been resolved yet, as only a PR has been created. Please reopen it.

**Comment by ash0923** [comment]
@sahksas すみません，ありがとうございます！firefox branch使ってみます！

**Comment by masachika-kamada** [comment]
The reflection in the store has been completed.
https://addons.mozilla.org/ja/firefox/addon/chatgpt-ctrl-enter-sender/
